title = "CyberTractor Challenge"
baseURL = "https://cybertractorchallenge.org"
languageCode = "en-us"
theme = ["ananke"]
resourceDir = "../resources"
publishDir = 'docs'
canonifyurls = true
paginate = 10

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "CyberTractor Challenge"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "CyberTractor Challenge"
  favicon = ""
  site_logo = ""
  description = "A website to document and share the CyberTractor Challenge event with the wider cybersecurity communities"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 2

[[params.ananke_socials]]
name = "LinkedIn"
url = "https://www.linkedin.com/company/99360447/admin/feed/posts/"
# name = "CyberTruck Challenge"
# url = "https://www.cybertruckchallenge.org/"

# Define the main menu
[[menu.main]]
name = "Challenges"
url = "#"
weight = 1
identifier = "challenges"

# Define a child item of the Challenges dropdown
[[menu.main]]
name = "CyberTruck Challenge"
url = "https://www.cybertruckchallenge.org/"
weight = 1
parent = "challenges"
[[menu.main]]
name = "CyberAuto Challenge"
url = "https://www.cyberauto-challenge.org/"
weight = 1
parent = "challenges"
[[menu.main]]
name = "CyberMedical Challenge"
url = "https://www.cybermedicalchallenge.org/"
weight = 1
parent = "challenges"


[markup.goldmark.renderer]
unsafe= true
