title = "CyberTractor Challenge"
baseURL = "https://cybertractorchallenge.org"
languageCode = "en-us"
theme = ["ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "CyberTractor Challenge"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "CyberTractor Challenge"
  favicon = ""
  site_logo = ""
  description = "A website to document and share the CyberTractor Challenge event with the wider cybersecurity communities"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 2

[[params.ananke_socials]]
#name = "LinkedIn"
#url = "https://linkedin.com/cybertractorchallenge"
name = "CyberTruck Challenge"
url = "https://www.cybertruckchallenge.org/"

[markup.goldmark.renderer]
unsafe= true
